spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # org.hibernate.dialect.SQLServerDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true


  datasource:
    #    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=sqlserver_db
    #    username: aurva
    #    password: Aurva123
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:postgresql://localhost:5432/flowable # host.docker.internal for Docker ( Mac )
    username: postgres
    password: p0stgr3s
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

